# Generated by Django 6.0.4 on 2026-04-28 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_family_table_rsvp_family_rsvp_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='table',
        ),
        migrations.AddField(
            model_name='family',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='api.table'),
        ),
    ]
